# my global config
global:
  scrape_interval: 2s # Set the scrape interval to every 2 seconds. Default is every 1 minute.
  evaluation_interval: 2s # Evaluate rules every 2 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: 
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# Configure the storage location
# storage:
#   tsdb:
#     path: "z:" # Change this to your mounted NAS path

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "yoctohub_sensors"
    static_configs:
      - targets: ["localhost:8000"]

  - job_name: "thermocouple_sensors"
    static_configs:
      - targets: ["localhost:8001"]